
spring:
  r2dbc:
    url: "r2dbc:postgresql://127.0.0.1:5432/bookingdb?currentSchema=devDb"
    username: "postgres"
    password: "1234"
    pool:
      initial-size: 30
      max-size: 60
  profiles:
    active: "dev"
  graphql:
    graphiql:
      enabled: true